### ISSUE TITLE
{crul} is causing segfaults in {curl} downloads

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/weatherOz#72]
See https://github.com/jeroen/curl/issues/338#issuecomment-2124777988

Refactor to {httr2} before releasing on CRAN.

**Comment by jeroen** [comment]
Maybe you don't have to refactor but you can avoid the problem.

The issue is caused by the fact that there is a bug in versions 8.6.0-8.7.1 of libcurl when the same "curl handle" is used for both http and ftp downloads. It seems that the crul package does this. 

Another solution is to update to libcurl 8.8.0.

**Comment by adamhsparks** [comment]
Ah! Thank you for the further clarification @jeroen. We should be able to work around that by just using a new handle for the different download methods, no?

**Comment by adamhsparks** [comment]
I can upgrade, but want to be sure that it's not an issue for anyone else using the package, better safe than sorry.

**Comment by adamhsparks** [comment]
If I understand correctly, yes, https://docs.ropensci.org/crul/reference/handle.html
