### ISSUE TITLE
OceaniaR Hackathon :: Open to collaboration?

### ISSUE THREAD

**Issue by deanmarchiori** [ropensci/weatherOz#84]
Hi Team,

On October 21 a group of R developers will be meeting in Melbourne for an R themed hackathon style day. The focus will be on projects and participants from the Oceania region. see here: https://statsocaus.github.io/oceaniaR-hack/  

We wanted to see if there were any issues or contributions that would be welcome from a group of R users looking to collaborate over a 1 day period that would help this project?  

Keen to see how we can help :) 

Regards

Dean.

**Comment by adamhsparks** [comment]
Pending my travel options, I may be able to attend this. I'm planning to be at WOMBAT for sure.

Getting the AGCD (formerly AWAP) data could be a nice add-on? It's available under a Creative Commons Licence, https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f1801_8183_3094_1341

Best I can tell they (NCI) don't mind if you programmatically access data, 
>Offering a variety of services, THREDDS enables users to access individual files and utilize advanced features such as OpenDAP, NetCDF subsetting, and OGC WCS and WMS. Additionally, the server is programmatically accessible, making it a preferred choice for many advanced tools and portals. 

See: https://thredds.nci.org.au/thredds/fileServer/thredds-readme/thredds_readme.txt

@bozaah, is there another data set you can think of?

**Comment by jimjam-slam** [comment]
Now that I'm back from leave, I should separately mention the [ACORN-SAT](http://www.bom.gov.au/climate/data/acorn-sat/) support I proposed, @adamhsparks! Happy to work on this separately in the coming weeks, but it could also be appropriate for OceaniaR. It's FTP access.

I _believe_ it's Creative Commons, but I'd have to confirm: the notice on the bottom of the ACORN-SAT pages is "Unless otherwise noted, all maps, graphs and diagrams in this page are licensed under the [Creative Commons Attribution 4.0 International Licence](https://creativecommons.org/licenses/by/4.0/)", but I don't see a separate licence on the dataset itself (although it is on the public FTP).

**Comment by bozaah** [comment]
Hi all, 
Just back from leave too. Thanks @deanmarchiori, @adamhspark and @jimjam-slam.

I think if we can implement the functionality to download data from the THREDDS, it could be interesting to add access to the ['application ready' future climate projection datasets](https://www.climatechangeinaustralia.gov.au/en/obtain-data/download-datasets/#ARD) for [daily](https://data-cbr.csiro.au/thredds/catalog/catch_all/oa-aus5km/Climate_Change_in_Australia_User_Data/Application_Ready_Data_Gridded_Daily/catalog.html) and [monthly](https://data-cbr.csiro.au/thredds/catalog/catch_all/oa-aus5km/Climate_Change_in_Australia_User_Data/Application_Ready_Data_Gridded_Monthly/catalog.html) grids, although it is not clear from the website what licensing CSIRO has released these under.  Personally, I have also been using the [ANUClimate 2.0 gridded datasets](https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f2576_7854_4065_1457). The ANU folks are also very responsive when issues/bugs are identified so that is plus. Data are released under a Creative Commons Licence and is available for daily and monthly periods.

**Comment by adamhsparks** [comment]
THREDDS is CC-NC 4.0, see "Access constraints" in the page I linked to: https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f1801_8183_3094_1341

But the ANUClimate set looks nice too!

**Comment by adamhsparks** [comment]
There is also this dataset from CSIRO, "Hourly near-surface air temperature grids for Australia" published <https://link.springer.com/article/10.1007/s00382-024-07340-w> and available here <https://doi.org/10.25919/1sgg-b556>, that could be interesting pending the ability to programatically access. The licence is favourable, CC-BY-SA 4.0 (but since we are redistributing that shouldn't be an issue for us).

**Comment by deanmarchiori** [comment]
Hello! I don't think we got around to doing much here during the event, but I like the above suggestions for future work. Thanks!
